#! /usr/bin/env python3
#---------------------------------
#   Plots errors of experiments
#      obtained from iModel output
#   Pedro Peixoto (ppeixoto@usp.br)
#   May 2019
#----------------------------------

import sys
import os
import re
import string
import numpy as np

#imodel routines
import imodel_data
from imodel_data import imodelData 

# input filename
input_filename = 'errors.txt'
if len(sys.argv) <= 1 :
	print("I need 1 argument:")
	print("A filename containing the errors generated by imodel")
	sys.exit(1)
	
if len(sys.argv) > 1:
	input_filename = sys.argv[1]
	
data=imodelData(input_filename)

#Dictionary for fancy naming
data.FancyNames("fancy.csv") #Load naming convention

# User inputs
data.UserOptions("options.csv") #load user options

#User filters
data.UserFilters("filter.csv") #load user filters

#Organize all options
data.OrganizeOptions()

# Decide what to plot based on
# load user inner/outer loops for plotting - inner is within legend (each graph), outer
# Configure the figures to be plotted
fig = data.BuildFigures()

