#! /usr/bin/env python3
#---------------------------------
#   Plots errors of experiments
#      obtained from iModel output
#   Pedro Peixoto (ppeixoto@usp.br)
#   Novembre 2018
#----------------------------------


import sys
import os
import re
import string
import numpy as np

import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

#imodel routines
import imodel_data_evol
from imodel_data_evol import imodelData 

# input filename
input_filename = 'errors.txt'
if len(sys.argv) <= 2 :
	print("I need as 1st argument:")
	print("  A filename containing the options of graphing (see options_template.csv")
	print("Then I need as argument the evolution files:")
	print(" containing the errors generated by imodel")
	sys.exit(1)

opt_filename = sys.argv[1]
input_files = sys.argv[2:]


#Get data
data=imodelData(input_files)

#Calculate 10-folding times, if required
data.CalcFoldingTimes()

#Dictionary for fancy naming
data.FancyNames("fancy.csv") #Load naming convention

# User inputs
data.UserOptions(opt_filename) #load user options

#User filters
data.UserFilters("filter.csv") #load user filters

#Organize all options
data.OrganizeOptions()