%% Import data from text file.
% Script for importing data from the following text file:
%
%    /scratch/pd300/Work/Programas/iModel/matlab/GLWBALevol-glevel7.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/12 14:23:37

%% Initialize variables.
filename = '/scratch/pd300/Work/Programas/iModel/matlab/GLWBALevol-glevel7.txt';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ds = dataset(dataArray{1:end-1}, 'VarNames', {'timedys','newerrormax_h','newerror2_h','newerrormax_u','newerror2_u','trskerrormax_h','trskerror2_h','trskerrormax_u','trskerror2_u'});
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;