%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/pedrosp/Work/Programas/iModel/matlab/tc6.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/11 15:41:22

%% Initialize variables.
filename = '/home/pedrosp/Work/Programas/iModel/matlab/tc6.txt';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: text (%s)
%   column19: text (%s)
%	column20: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ds = dataset(dataArray{1:end-1}, 'VarNames', {'Glevel','n','mvdist','tcase','time1','ntime','dts','cfl','timedys','errormax_h','error2_h','errormax_u','error2_u','mass','Penergy','Kenergy','Tenergy','method','swmname','grid'});
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;