%% Import data from text file.
% Script for importing data from the following text file:
%
%    /scratch/pd300/Work/Programas/iModel/matlab/swm_loc_trunc_errors.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/21 18:15:38

%% Initialize variables.
filename = '/scratch/pd300/Work/Programas/iModel/matlab/swm_loc_trunc_errors.txt';
delimiter = ' ';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%s)
%   column7: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ds = dataset(dataArray{1:end-1}, 'VarNames', {'Operator','Mesh','MaxErrorRel','RMSError','MaxError','Methods','Grid'});
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

[n, m]=size(ds);
for i=1:n
   a=cell2mat(ds.Grid(i));
   b=a(end:end);
   c=(a(1:end-1));
   ds.Glevel(i)=str2num(b);
   ds.Grid(i)=cellstr(c);
end
clearvars a b c i