%% Initialize variables
function grd=initialize_grid(nx, ny, lx, ly, nt, Tmax)

dt=Tmax/nt;

dx=lx/nx;
dy=ly/ny;

% Vorticity points
xz(1:nx)=dx*(1:(nx))-dx;
yz(1:ny)=dy*(1:(ny))-dy;

% Height points
xh(1:nx)=xz+dx*0.5;
yh(1:ny)=yz+dy*0.5;

% Velocity points
xu(1:nx)=xz;
yu(1:ny)=yz+dy*0.5;
xv(1:nx)=xz+dx*0.5;
yv(1:ny)=yz;

grd=struct(...
    'nx', nx, ... 
    'ny', ny, ... 
    'lx', lx, ...
    'ly', ly, ...
    'dx', lx/nx, ...
    'dy', ly/ny, ...
    'xh', xh, ...
    'yh', yh, ...
    'xu', xu, ...
    'yu', yu, ...
    'xv', xv, ...
    'yv', yv, ...
    'xz', xz, ...
    'yz', yz, ...
    'dt', dt, ...
    'nt', nt ...
    );

end